### ISSUE TITLE
Documentation Entropy

### ISSUE THREAD

**Issue by rigbypc** [marouen-lamiri/SOEN-6611#27]
- Finding 5: Discussion of code have low entropy, how does it compare to the actual program entropy? Seems that discussions have even lower entropy than code. Discussion text is very limited.
 - Finding 6: Code elements discussed on stackoverflow have very low entropy. Likely because people ask the same questions and certain code elements are more difficult to understand as well as more useful.

@arashiqurrahman

**Comment by mrsumitbd** [comment]
Please refer to #21

**Comment by mrsumitbd** [comment]
Experimentation completed and shown in #21
